package com.za.tutorial.ga.cs;
import javax.swing.DefaultListModel;


	
	public class GUI2 extends javax.swing.JFrame {

	    /**
	     * Creates new form NewJFrame
	     */
	    public GUI2() {
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        gaschedules = new javax.swing.JTabbedPane();
	        objectsNumbers = new javax.swing.JPanel();
	        jLabel1 = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	        jLabel3 = new javax.swing.JLabel();
	        jLabel4 = new javax.swing.JLabel();
	        roomsNumber = new javax.swing.JTextField();
	        meetingTimesnumber = new javax.swing.JTextField();
	        instructorsNumber = new javax.swing.JTextField();
	        departmentNumber = new javax.swing.JTextField();
	        nextobjectsn = new javax.swing.JButton();
	        aboutus = new javax.swing.JButton();
	        database = new javax.swing.JButton();
	        objectsInformations = new javax.swing.JPanel();
	        jLabel5 = new javax.swing.JLabel();
	        jLabel6 = new javax.swing.JLabel();
	        jLabel7 = new javax.swing.JLabel();
	        roomsInfo = new javax.swing.JTextField();
	        meetingtimeInfo = new javax.swing.JTextField();
	        instructorsInfo = new javax.swing.JTextField();
	        addMeeting = new javax.swing.JButton();
	        addInstructor = new javax.swing.JButton();
	        addRoom = new javax.swing.JButton();
	        nextDept = new javax.swing.JButton();
	        backOnumbers = new javax.swing.JButton();
	        jScrollPane1 = new javax.swing.JScrollPane();
	        roomsList = new javax.swing.JList<>();
	        jScrollPane3 = new javax.swing.JScrollPane();
	        timeList = new javax.swing.JList<>();
	        jScrollPane8 = new javax.swing.JScrollPane();
	        instructorList = new javax.swing.JList<>();
	        departmens = new javax.swing.JPanel();
	        jTabbedPane2 = new javax.swing.JTabbedPane();
	        jPanel6 = new javax.swing.JPanel();
	        jLabel8 = new javax.swing.JLabel();
	        jLabel9 = new javax.swing.JLabel();
	        dinfo1 = new javax.swing.JTextField();
	        jButton10 = new javax.swing.JButton();
	        jTextField9 = new javax.swing.JTextField();
	        jButton14 = new javax.swing.JButton();
	        jButton15 = new javax.swing.JButton();
	        jTextField18 = new javax.swing.JTextField();
	        jLabel19 = new javax.swing.JLabel();
	        jScrollPane2 = new javax.swing.JScrollPane();
	        dept1 = new javax.swing.JList<>();
	        jPanel7 = new javax.swing.JPanel();
	        jLabel10 = new javax.swing.JLabel();
	        jLabel11 = new javax.swing.JLabel();
	        dinfo2 = new javax.swing.JTextField();
	        jButton11 = new javax.swing.JButton();
	        jTextField11 = new javax.swing.JTextField();
	        jButton16 = new javax.swing.JButton();
	        jButton17 = new javax.swing.JButton();
	        jTextField17 = new javax.swing.JTextField();
	        jLabel18 = new javax.swing.JLabel();
	        jScrollPane9 = new javax.swing.JScrollPane();
	        dept2 = new javax.swing.JList<>();
	        jPanel8 = new javax.swing.JPanel();
	        jLabel12 = new javax.swing.JLabel();
	        jLabel13 = new javax.swing.JLabel();
	        dinfo3 = new javax.swing.JTextField();
	        jButton12 = new javax.swing.JButton();
	        jTextField13 = new javax.swing.JTextField();
	        jButton18 = new javax.swing.JButton();
	        jButton19 = new javax.swing.JButton();
	        jLabel17 = new javax.swing.JLabel();
	        jTextField16 = new javax.swing.JTextField();
	        jScrollPane10 = new javax.swing.JScrollPane();
	        dept3 = new javax.swing.JList<>();
	        solution = new javax.swing.JPanel();
	        jScrollPane7 = new javax.swing.JScrollPane();
	        jTextArea1 = new javax.swing.JTextArea();
	        jLabel14 = new javax.swing.JLabel();
	        jLabel15 = new javax.swing.JLabel();
	        jLabel16 = new javax.swing.JLabel();
	        jButton13 = new javax.swing.JButton();
	        jLabel20 = new javax.swing.JLabel();
	        jLabel21 = new javax.swing.JLabel();
	        jLabel22 = new javax.swing.JLabel();
	        jLabel23 = new javax.swing.JLabel();
	        jLabel24 = new javax.swing.JLabel();
	        jLabel25 = new javax.swing.JLabel();
	        jButton1 = new javax.swing.JButton();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	        setResizable(false);

	        gaschedules.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
	        gaschedules.setEnabled(false);
	        gaschedules.setName(""); // NOI18N

	        jLabel1.setText("Rooms number :");

	        jLabel2.setText("Meeting times number :");

	        jLabel3.setText("Instructors number :");

	        jLabel4.setText("Departments number :");

	        roomsNumber.setText("");

	        meetingTimesnumber.setText("");
	        meetingTimesnumber.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                meetingTimesnumberActionPerformed(evt);
	            }
	        });

	        instructorsNumber.setText("");
	        instructorsNumber.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                instructorsNumberActionPerformed(evt);
	            }
	        });

	        departmentNumber.setText("");
	        departmentNumber.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                departmentNumberActionPerformed(evt);
	            }
	        });

	        nextobjectsn.setText("Next");
	        nextobjectsn.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                nextobjectsnActionPerformed(evt);
	            }
	        });

	        aboutus.setText("About us");
	        aboutus.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                aboutusActionPerformed(evt);
	            }
	        });

	        database.setText("Database");
	        database.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                databaseActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout objectsNumbersLayout = new javax.swing.GroupLayout(objectsNumbers);
	        objectsNumbers.setLayout(objectsNumbersLayout);
	        objectsNumbersLayout.setHorizontalGroup(
	            objectsNumbersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(objectsNumbersLayout.createSequentialGroup()
	                .addGap(92, 92, 92)
	                .addGroup(objectsNumbersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
	                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                .addGap(18, 18, 18)
	                .addGroup(objectsNumbersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                    .addComponent(instructorsNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
	                    .addComponent(departmentNumber)
	                    .addComponent(meetingTimesnumber)
	                    .addComponent(roomsNumber))
	                .addContainerGap(751, Short.MAX_VALUE))
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, objectsNumbersLayout.createSequentialGroup()
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addGroup(objectsNumbersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(database)
	                    .addGroup(objectsNumbersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                        .addComponent(aboutus, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
	                        .addComponent(nextobjectsn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
	                .addGap(27, 27, 27))
	        );
	        objectsNumbersLayout.setVerticalGroup(
	            objectsNumbersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(objectsNumbersLayout.createSequentialGroup()
	                .addGap(65, 65, 65)
	                .addGroup(objectsNumbersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addGroup(objectsNumbersLayout.createSequentialGroup()
	                        .addGroup(objectsNumbersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                            .addComponent(jLabel1)
	                            .addComponent(roomsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addGap(81, 81, 81)
	                        .addGroup(objectsNumbersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                            .addComponent(jLabel2)
	                            .addComponent(meetingTimesnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addGap(92, 92, 92)
	                        .addComponent(jLabel3))
	                    .addComponent(instructorsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGroup(objectsNumbersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, objectsNumbersLayout.createSequentialGroup()
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                        .addComponent(database)
	                        .addGap(18, 18, 18)
	                        .addComponent(aboutus)
	                        .addGap(18, 18, 18)
	                        .addComponent(nextobjectsn)
	                        .addGap(26, 26, 26))
	                    .addGroup(objectsNumbersLayout.createSequentialGroup()
	                        .addGap(84, 84, 84)
	                        .addGroup(objectsNumbersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                            .addComponent(departmentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jLabel4))
	                        .addContainerGap(150, Short.MAX_VALUE))))
	        );

	        gaschedules.addTab("Objects numbers", objectsNumbers);

	        jLabel5.setText("Rooms ID, Seating capacity");

	        jLabel6.setText("Meeting times ID, Time");

	        jLabel7.setText("Instructors ID, Name");

	        addMeeting.setText("Add");
	        addMeeting.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                addMeetingActionPerformed(evt);
	            }
	        });

	        addInstructor.setText("Add");
	        addInstructor.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                addInstructorActionPerformed(evt);
	            }
	        });

	        addRoom.setText("Add");
	        addRoom.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                addRoomActionPerformed(evt);
	            }
	        });

	        nextDept.setText("Next");
	        nextDept.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                nextDeptActionPerformed(evt);
	            }
	        });

	        backOnumbers.setText("Back");
	        backOnumbers.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                backOnumbersActionPerformed(evt);
	            }
	        });

	        jScrollPane1.setViewportView(roomsList);

	        jScrollPane3.setViewportView(timeList);

	        jScrollPane8.setViewportView(instructorList);

	        javax.swing.GroupLayout objectsInformationsLayout = new javax.swing.GroupLayout(objectsInformations);
	        objectsInformations.setLayout(objectsInformationsLayout);
	        objectsInformationsLayout.setHorizontalGroup(
	            objectsInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(objectsInformationsLayout.createSequentialGroup()
	                .addGap(49, 49, 49)
	                .addGroup(objectsInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addGroup(objectsInformationsLayout.createSequentialGroup()
	                        .addGap(0, 0, Short.MAX_VALUE)
	                        .addComponent(backOnumbers))
	                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, objectsInformationsLayout.createSequentialGroup()
	                        .addGroup(objectsInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addGroup(objectsInformationsLayout.createSequentialGroup()
	                                .addGroup(objectsInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
	                                    .addComponent(roomsInfo))
	                                .addGap(18, 18, 18)
	                                .addComponent(addRoom)))
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addGroup(objectsInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(objectsInformationsLayout.createSequentialGroup()
	                                .addGap(24, 24, 24)
	                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
	                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addGroup(objectsInformationsLayout.createSequentialGroup()
	                                .addComponent(meetingtimeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addGap(18, 18, 18)
	                                .addComponent(addMeeting)))
	                        .addGap(24, 24, 24)
	                        .addGroup(objectsInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addGroup(objectsInformationsLayout.createSequentialGroup()
	                                .addComponent(instructorsInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addGap(18, 18, 18)
	                                .addComponent(addInstructor))
	                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addGap(0, 0, Short.MAX_VALUE)))
	                .addGap(18, 18, 18)
	                .addComponent(nextDept)
	                .addGap(23, 23, 23))
	        );
	        objectsInformationsLayout.setVerticalGroup(
	            objectsInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(objectsInformationsLayout.createSequentialGroup()
	                .addGap(52, 52, 52)
	                .addGroup(objectsInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel5)
	                    .addComponent(jLabel6)
	                    .addComponent(jLabel7))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(objectsInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(roomsInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(meetingtimeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(instructorsInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(addMeeting)
	                    .addComponent(addInstructor)
	                    .addComponent(addRoom))
	                .addGap(18, 18, 18)
	                .addGroup(objectsInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
	                .addGroup(objectsInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(nextDept)
	                    .addComponent(backOnumbers))
	                .addGap(30, 30, 30))
	        );

	        gaschedules.addTab("Objects informations", objectsInformations);

	        jTabbedPane2.setEnabled(false);

	        jLabel8.setText("Courses number");

	        jLabel9.setText("Course ID,Course name,Instructors number,instructors,capacity");

	        jButton10.setText("Add");
	        jButton10.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton10ActionPerformed(evt);
	            }
	        });

	        jTextField9.setText("");
	        jTextField9.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField9ActionPerformed(evt);
	            }
	        });

	        jButton14.setText("Next");
	        jButton14.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton14ActionPerformed(evt);
	            }
	        });

	        jButton15.setText("Back");
	        jButton15.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton15ActionPerformed(evt);
	            }
	        });

	        jTextField18.setText("");

	        jLabel19.setText("Department name :");

	        jScrollPane2.setViewportView(dept1);

	        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
	        jPanel6.setLayout(jPanel6Layout);
	        jPanel6Layout.setHorizontalGroup(
	            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addComponent(jButton15)
	                .addGap(18, 18, 18)
	                .addComponent(jButton14)
	                .addGap(25, 25, 25))
	            .addGroup(jPanel6Layout.createSequentialGroup()
	                .addGap(67, 67, 67)
	                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(jPanel6Layout.createSequentialGroup()
	                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(18, 18, 18)
	                        .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
	                    .addGroup(jPanel6Layout.createSequentialGroup()
	                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
	                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(dinfo1, javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
	                        .addGap(18, 18, 18)
	                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jButton10)
	                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
	                .addContainerGap(617, Short.MAX_VALUE))
	        );
	        jPanel6Layout.setVerticalGroup(
	            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel6Layout.createSequentialGroup()
	                .addGap(13, 13, 13)
	                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel19)
	                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addComponent(jLabel9)
	                .addGap(18, 18, 18)
	                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(dinfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jButton10))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
	                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jButton14)
	                    .addComponent(jButton15))
	                .addGap(32, 32, 32))
	        );

	        jTabbedPane2.addTab("Departmen 1", jPanel6);

	        jLabel10.setText("Courses number");

	        jLabel11.setText("Course ID,Course name,Instructors number,instructors,capacity");

	        jButton11.setText("Add");
	        jButton11.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton11ActionPerformed(evt);
	            }
	        });

	        jTextField11.setText("");
	        jTextField11.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField11ActionPerformed(evt);
	            }
	        });

	        jButton16.setText("Next");
	        jButton16.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton16ActionPerformed(evt);
	            }
	        });

	        jButton17.setText("Back");
	        jButton17.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton17ActionPerformed(evt);
	            }
	        });

	        jTextField17.setText("");
	        jTextField17.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField17ActionPerformed(evt);
	            }
	        });

	        jLabel18.setText("Department name :");

	        jScrollPane9.setViewportView(dept2);

	        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
	        jPanel7.setLayout(jPanel7Layout);
	        jPanel7Layout.setHorizontalGroup(
	            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addComponent(jButton17)
	                .addGap(18, 18, 18)
	                .addComponent(jButton16)
	                .addGap(34, 34, 34))
	            .addGroup(jPanel7Layout.createSequentialGroup()
	                .addGap(67, 67, 67)
	                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addGroup(jPanel7Layout.createSequentialGroup()
	                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(18, 18, 18)
	                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(1, 1, 1))
	                    .addGroup(jPanel7Layout.createSequentialGroup()
	                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addComponent(dinfo2)
	                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)))
	                        .addGap(18, 18, 18)
	                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jButton11)
	                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
	                .addContainerGap(617, Short.MAX_VALUE))
	        );
	        jPanel7Layout.setVerticalGroup(
	            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel7Layout.createSequentialGroup()
	                .addGap(22, 22, 22)
	                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel18)
	                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel10)
	                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addComponent(jLabel11)
	                .addGap(18, 18, 18)
	                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(dinfo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jButton11))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
	                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jButton16)
	                    .addComponent(jButton17))
	                .addGap(28, 28, 28))
	        );

	        jTabbedPane2.addTab("Department 2", jPanel7);

	        jLabel12.setText("Courses number");

	        jLabel13.setText("Course ID,Course name,Instructors number,instructors,capacity");

	        jButton12.setText("Add");
	        jButton12.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton12ActionPerformed(evt);
	            }
	        });

	        jTextField13.setText("");
	        jTextField13.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField13ActionPerformed(evt);
	            }
	        });

	        jButton18.setText("Next");
	        jButton18.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton18ActionPerformed(evt);
	            }
	        });

	        jButton19.setText("Back");
	        jButton19.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton19ActionPerformed(evt);
	            }
	        });

	        jLabel17.setText("Department name :");

	        jTextField16.setText("");
	        jTextField16.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField16ActionPerformed(evt);
	            }
	        });

	        jScrollPane10.setViewportView(dept3);

	        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
	        jPanel8.setLayout(jPanel8Layout);
	        jPanel8Layout.setHorizontalGroup(
	            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addComponent(jButton19)
	                .addGap(18, 18, 18)
	                .addComponent(jButton18)
	                .addGap(33, 33, 33))
	            .addGroup(jPanel8Layout.createSequentialGroup()
	                .addGap(67, 67, 67)
	                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(jPanel8Layout.createSequentialGroup()
	                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(18, 18, 18)
	                        .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
	                    .addGroup(jPanel8Layout.createSequentialGroup()
	                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
	                            .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(dinfo3, javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
	                        .addGap(18, 18, 18)
	                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jButton12)
	                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
	                .addContainerGap(617, Short.MAX_VALUE))
	        );
	        jPanel8Layout.setVerticalGroup(
	            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel8Layout.createSequentialGroup()
	                .addGap(16, 16, 16)
	                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel17)
	                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addComponent(jLabel13)
	                .addGap(18, 18, 18)
	                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(dinfo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jButton12))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
	                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jButton18)
	                    .addComponent(jButton19))
	                .addGap(29, 29, 29))
	        );

	        jTabbedPane2.addTab("Department 3", jPanel8);

	        javax.swing.GroupLayout departmensLayout = new javax.swing.GroupLayout(departmens);
	        departmens.setLayout(departmensLayout);
	        departmensLayout.setHorizontalGroup(
	            departmensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jTabbedPane2)
	        );
	        departmensLayout.setVerticalGroup(
	            departmensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jTabbedPane2)
	        );

	        gaschedules.addTab("Departments", departmens);

	        jTextArea1.setColumns(20);
	        jTextArea1.setRows(5);
	        jScrollPane7.setViewportView(jTextArea1);

	        jLabel14.setText("Elite Schudule");

	        jLabel15.setText("Generations number :");

	        jLabel16.setText("Excution time :");

	        jButton13.setText("Home page");
	        jButton13.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton13ActionPerformed(evt);
	            }
	        });

	        jLabel22.setText("Fitness score:");

	        jLabel23.setText("Conflicts:");

	        jButton1.setText("Extract");

	        javax.swing.GroupLayout solutionLayout = new javax.swing.GroupLayout(solution);
	        solution.setLayout(solutionLayout);
	        solutionLayout.setHorizontalGroup(
	            solutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(solutionLayout.createSequentialGroup()
	                .addGap(413, 413, 413)
	                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, solutionLayout.createSequentialGroup()
	                .addContainerGap(325, Short.MAX_VALUE)
	                .addGroup(solutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, solutionLayout.createSequentialGroup()
	                        .addGroup(solutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
	                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addGroup(solutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
	                        .addGap(87, 87, 87)
	                        .addGroup(solutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addGap(18, 18, 18)
	                        .addGroup(solutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addGap(207, 207, 207))
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, solutionLayout.createSequentialGroup()
	                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(18, 18, 18)
	                        .addComponent(jButton13)
	                        .addGap(31, 31, 31))
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, solutionLayout.createSequentialGroup()
	                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(84, 84, 84))))
	        );
	        solutionLayout.setVerticalGroup(
	            solutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(solutionLayout.createSequentialGroup()
	                .addGap(12, 12, 12)
	                .addComponent(jLabel14)
	                .addGap(18, 18, 18)
	                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(18, 18, 18)
	                .addGroup(solutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel15)
	                    .addComponent(jLabel20)
	                    .addComponent(jLabel22)
	                    .addComponent(jLabel24))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(solutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel16)
	                    .addComponent(jLabel21)
	                    .addComponent(jLabel23)
	                    .addComponent(jLabel25))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(solutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jButton13)
	                    .addComponent(jButton1))
	                .addContainerGap(35, Short.MAX_VALUE))
	        );

	        gaschedules.addTab("Solution", solution);

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(gaschedules)
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(gaschedules, javax.swing.GroupLayout.Alignment.TRAILING)
	        );

	        gaschedules.getAccessibleContext().setAccessibleName("");

	        pack();
	    }// </editor-fold>                        

	    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {                                          
	        gaschedules.setSelectedIndex(0);
	    }                                         

	    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {                                             
	        // TODO add your handling code here:
	    }                                            

	    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {                                          
	        jTabbedPane2.setSelectedIndex(1);
	    }                                         

	    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {                                          
	        gaschedules.setSelectedIndex(3);
	    }                                         

	    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {                                             
	        // TODO add your handling code here:
	    }                                            

	    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {                                             
	        // TODO add your handling code here:
	    }                                            

	    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {                                          
	        jTabbedPane2.setSelectedIndex(0);
	    }                                         

	    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {                                          
	        jTabbedPane2.setSelectedIndex(2);
	    }                                         

	    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {                                             
	        // TODO add your handling code here:
	    }                                            

	    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {                                          
	        gaschedules.setSelectedIndex(2);
	    }                                         

	    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {                                          
	        jTabbedPane2.setSelectedIndex(1);
	    }                                         

	    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {                                            
	        // TODO add your handling code here:
	    }                                           

	    private void databaseActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        // TODO add your handling code here:
	    }                                        

	    private void aboutusActionPerformed(java.awt.event.ActionEvent evt) {                                        
	        // TODO add your handling code here:
	    }                                       

	    private void nextobjectsnActionPerformed(java.awt.event.ActionEvent evt) {                                             
	        gaschedules.setSelectedIndex(1);
	    }                                            

	    private void departmentNumberActionPerformed(java.awt.event.ActionEvent evt) {                                                 
	        // TODO add your handling code here:
	    }                                                

	    private void instructorsNumberActionPerformed(java.awt.event.ActionEvent evt) {                                                  
	        // TODO add your handling code here:
	    }                                                 

	    private void meetingTimesnumberActionPerformed(java.awt.event.ActionEvent evt) {                                                   
	        // TODO add your handling code here:
	    }                                                  

	    private void backOnumbersActionPerformed(java.awt.event.ActionEvent evt) {                                             
	        gaschedules.setSelectedIndex(0);
	    }                                            

	    private void nextDeptActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        gaschedules.setSelectedIndex(2);
	    }                                        
	        DefaultListModel mod= new DefaultListModel();
	        DefaultListModel mod1= new DefaultListModel();
	        DefaultListModel mod2= new DefaultListModel();
	    private void addRoomActionPerformed(java.awt.event.ActionEvent evt) {                                        
	        roomsList.setModel(mod);
	        mod.addElement(roomsInfo.getText());
	        roomsInfo.setText("");
	    }                                       

	    private void addMeetingActionPerformed(java.awt.event.ActionEvent evt) {                                           
	        timeList.setModel(mod1);
	        mod1.addElement(meetingtimeInfo.getText());
	        meetingtimeInfo.setText("");
	    }                                          

	    private void addInstructorActionPerformed(java.awt.event.ActionEvent evt) {                                              
	        instructorList.setModel(mod2);
	        mod2.addElement(instructorsInfo.getText());
	        instructorsInfo.setText("");
	    }                                             
	DefaultListModel mod3= new DefaultListModel();
	DefaultListModel mod4= new DefaultListModel();
	DefaultListModel mod5= new DefaultListModel();
	    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
	        dept1.setModel(mod3);
	        mod3.addElement(dinfo1.getText());
	        dinfo1.setText("");
	    }                                         

	    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
	        dept2.setModel(mod4);
	        mod4.addElement(dinfo2.getText());
	        dinfo2.setText("");
	    }                                         

	    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {                                          
	        dept3.setModel(mod5);
	        mod5.addElement(dinfo3.getText());
	        dinfo3.setText("");
	    }                                         

	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	       
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new GUI2().setVisible(true);
	            }
	        });
	    }

	    // Variables declaration - do not modify                     
	    private javax.swing.JButton aboutus;
	    private javax.swing.JButton addInstructor;
	    private javax.swing.JButton addMeeting;
	    private javax.swing.JButton addRoom;
	    private javax.swing.JButton backOnumbers;
	    private javax.swing.JButton database;
	    private javax.swing.JPanel departmens;
	    private javax.swing.JTextField departmentNumber;
	    private javax.swing.JList<String> dept1;
	    private javax.swing.JList<String> dept2;
	    private javax.swing.JList<String> dept3;
	    private javax.swing.JTextField dinfo1;
	    private javax.swing.JTextField dinfo2;
	    private javax.swing.JTextField dinfo3;
	    private javax.swing.JTabbedPane gaschedules;
	    private javax.swing.JList<String> instructorList;
	    private javax.swing.JTextField instructorsInfo;
	    private javax.swing.JTextField instructorsNumber;
	    private javax.swing.JButton jButton1;
	    private javax.swing.JButton jButton10;
	    private javax.swing.JButton jButton11;
	    private javax.swing.JButton jButton12;
	    private javax.swing.JButton jButton13;
	    private javax.swing.JButton jButton14;
	    private javax.swing.JButton jButton15;
	    private javax.swing.JButton jButton16;
	    private javax.swing.JButton jButton17;
	    private javax.swing.JButton jButton18;
	    private javax.swing.JButton jButton19;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel10;
	    private javax.swing.JLabel jLabel11;
	    private javax.swing.JLabel jLabel12;
	    private javax.swing.JLabel jLabel13;
	    private javax.swing.JLabel jLabel14;
	    private javax.swing.JLabel jLabel15;
	    private javax.swing.JLabel jLabel16;
	    private javax.swing.JLabel jLabel17;
	    private javax.swing.JLabel jLabel18;
	    private javax.swing.JLabel jLabel19;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel20;
	    private javax.swing.JLabel jLabel21;
	    private javax.swing.JLabel jLabel22;
	    private javax.swing.JLabel jLabel23;
	    private javax.swing.JLabel jLabel24;
	    private javax.swing.JLabel jLabel25;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JLabel jLabel5;
	    private javax.swing.JLabel jLabel6;
	    private javax.swing.JLabel jLabel7;
	    private javax.swing.JLabel jLabel8;
	    private javax.swing.JLabel jLabel9;
	    private javax.swing.JPanel jPanel6;
	    private javax.swing.JPanel jPanel7;
	    private javax.swing.JPanel jPanel8;
	    private javax.swing.JScrollPane jScrollPane1;
	    private javax.swing.JScrollPane jScrollPane10;
	    private javax.swing.JScrollPane jScrollPane2;
	    private javax.swing.JScrollPane jScrollPane3;
	    private javax.swing.JScrollPane jScrollPane7;
	    private javax.swing.JScrollPane jScrollPane8;
	    private javax.swing.JScrollPane jScrollPane9;
	    private javax.swing.JTabbedPane jTabbedPane2;
	    private javax.swing.JTextArea jTextArea1;
	    private javax.swing.JTextField jTextField11;
	    private javax.swing.JTextField jTextField13;
	    private javax.swing.JTextField jTextField16;
	    private javax.swing.JTextField jTextField17;
	    private javax.swing.JTextField jTextField18;
	    private javax.swing.JTextField jTextField9;
	    private javax.swing.JTextField meetingTimesnumber;
	    private javax.swing.JTextField meetingtimeInfo;
	    private javax.swing.JButton nextDept;
	    private javax.swing.JButton nextobjectsn;
	    private javax.swing.JPanel objectsInformations;
	    private javax.swing.JPanel objectsNumbers;
	    private javax.swing.JTextField roomsInfo;
	    private javax.swing.JList<String> roomsList;
	    private javax.swing.JTextField roomsNumber;
	    private javax.swing.JPanel solution;
	    private javax.swing.JList<String> timeList;
	    // End of variables declaration                   
	}


